spring:
  datasource:
    url: jdbc:sqlite:db.sqlite
    driver-class-name: org.sqlite.JDBC
  jpa:
    hibernate:
      ddl-auto: update  # 완성 후 update로 변경
    show-sql: false
    database-platform: org.hibernate.community.dialect.SQLiteDialect

##     완성 후 여기부터 아래 끝까지 주석
#    defer-datasource-initialization: false
#  sql:
#    init:
#      mode: always
